version: '3.9'

services:
  db:
    image: postgres:15.0-alpine
    command: postgres -c 'max_connections=5000'
    restart: on-failure
    volumes:
      - ./.postgres_data/:/var/lib/postgresql/data
    ports:
      - "5435:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust

  migrate:
    image: migrate/migrate
    entrypoint: "migrate -path /tmp/migrations -database postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}?sslmode=${DB_SSL_MODE}"
    command: up
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA_HOST}:${KAFKA_PORT},EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  client1:
    build: ./txclient
    tty: true
    ports:
     - "8088:8088"
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - APP_PORT=8088
      - KAFKA_PORT=${KAFKA_PORT}
      - KAFKA_HOST=${KAFKA_HOST}
      - TX_CLIENT_NUM=1

  client2:
    build: ./txclient
    tty: true
    ports:
      - "8089:8089"
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - APP_PORT=8089
      - KAFKA_PORT=${KAFKA_PORT}
      - KAFKA_HOST=${KAFKA_HOST}
      - TX_CLIENT_NUM=2

  server:
    build: ./txserver
    tty: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    depends_on:
      - kafka
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_PORT=${APP_PORT}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - TX_CLIENTS_COUNT=2

